# Generated by Django 5.2.4 on 2025-07-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dental_Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('erkek', 'Erkek'), ('kadın', 'Kadın')], max_length=5)),
                ('day', models.CharField(choices=[('pazartesi', 'Pazartesi'), ('salı', 'Salı'), ('çarşamba', 'Çarşamba'), ('perşembe', 'Perşembe'), ('cuma', 'Cuma')], max_length=9)),
                ('time', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hair_Dresser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('pazartesi', 'Pazartesi'), ('salı', 'Salı'), ('çarşamba', 'Çarşamba'), ('perşembe', 'Perşembe'), ('cuma', 'Cuma')], max_length=9)),
                ('time', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policlinic', models.TextField(choices=[('dahiliye', 'Dahiliye'), ('kbb', 'KBB'), ('onkoloji', 'Onkoloji'), ('psikoloji', 'Psikoloji'), ('radyoloji', 'Radyoloji'), ('nöroloji', 'Nöroloji'), ('kardiyoloji', 'Kardiyoloji')], max_length=20)),
                ('gender', models.CharField(choices=[('erkek', 'Erkek'), ('kadın', 'Kadın')], max_length=5)),
                ('day', models.CharField(choices=[('pazartesi', 'Pazartesi'), ('salı', 'Salı'), ('çarşamba', 'Çarşamba'), ('perşembe', 'Perşembe'), ('cuma', 'Cuma')], max_length=9)),
                ('time', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('erkek', 'Erkek'), ('kadın', 'Kadın')], max_length=5)),
                ('day', models.CharField(choices=[('pazartesi', 'Pazartesi'), ('salı', 'Salı'), ('çarşamba', 'Çarşamba'), ('perşembe', 'Perşembe'), ('cuma', 'Cuma')], max_length=9)),
                ('time', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
