# Generated by Django 5.2.4 on 2025-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=20)),
                ('issue', models.TextField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='pc_type',
            field=models.CharField(blank=True, choices=[('masaüstü', 'Masaüstü'), ('laptop', 'Laptop')], max_length=8, null=True),
        ),
    ]
