# Generated by Django 5.2.4 on 2025-07-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_computer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pc_Type',
        ),
        migrations.AlterField(
            model_name='computer',
            name='pc_type',
            field=models.CharField(choices=[('masaüstü', 'Masaüstü'), ('laptop', 'Laptop')], max_length=8),
        ),
    ]
