# Generated by Django 5.2.4 on 2025-07-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_delete_pc_type_alter_computer_pc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='playerequipment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='playerequipment',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='smartwatch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='smartwatch',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='surname',
        ),
    ]
