# Generated by Django 5.2.4 on 2025-08-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_playerequipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], max_length=15, null=True),
        ),
    ]
