# Generated by Django 5.2.4 on 2025-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_computer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerequipment',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], max_length=15, null=True),
        ),
    ]
