# Generated by Django 5.2.4 on 2025-08-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_playerequipment_status_smartphone_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], default='beklemede', max_length=15),
        ),
        migrations.AlterField(
            model_name='playerequipment',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], default='beklemede', max_length=15),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], default='beklemede', max_length=15),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], default='beklemede', max_length=15),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], default='beklemede', max_length=15),
        ),
        migrations.AlterField(
            model_name='tv',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('işleme alındı', 'İşleme Alındı'), ('hata giderildi', 'Hata Giderildi')], default='beklemede', max_length=15),
        ),
    ]
